FIX: Patch out jax.lib.xla_extension.XlaRuntimeError
* Avoid:
  AttributeError: jax.lib.xla_extension.XlaRuntimeError has been removed; use
  jax.errors.JaxRuntimeError instead.